# Generated by Django 3.0.8 on 2020-09-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200911_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
